"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { requireContributor } from "@/lib/roles";
import { BADGE_SLOTS, type Badge } from "@/data/marketplace";
import { isAreaUnit } from "@/lib/money";
import { LISTING_IMAGES_BUCKET, MAX_IMAGES } from "@/lib/listingImages";
import {
  LISTING_VIDEOS_BUCKET,
  MAX_VIDEOS,
} from "@/lib/listingVideos";

export type FormState = { error?: string; message?: string };

const KINDS = ["plot", "house", "apt", "agri"];
const TONES = ["ok", "warn", "none"];

function readBadges(formData: FormData): Badge[] {
  const badges: Badge[] = [];
  // The same document twice reads as a mistake on the card, so keep one.
  const seen = new Set<string>();

  for (let i = 0; i < BADGE_SLOTS; i++) {
    const label = String(formData.get(`badgeLabel${i}`) ?? "").trim();
    if (!label) continue;
    const key = label.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    const tone = String(formData.get(`badgeTone${i}`) ?? "none");
    badges.push({
      label,
      tone: (TONES.includes(tone) ? tone : "none") as Badge["tone"],
    });
  }

  return badges;
}

/** A money or size field: a positive number, or null when left empty. */
function readNumber(formData: FormData, key: string): number | null {
  const raw = String(formData.get(key) ?? "").trim();
  if (!raw) return null;
  const n = Number(raw);
  return Number.isFinite(n) && n > 0 ? n : null;
}

/** Uploaded photo paths, in the order the form shows them (cover first). */
function readImages(formData: FormData): string[] {
  return String(formData.get("images") ?? "")
    .split(",")
    .map((p) => p.trim())
    // Paths are generated by the uploader; keep the shape it produces.
    .filter((p) => /^[A-Za-z0-9._-]+$/.test(p))
    .slice(0, MAX_IMAGES);
}

/** Uploaded video paths, in the order the form shows them. */
function readVideos(formData: FormData): string[] {
  return String(formData.get("videos") ?? "")
    .split(",")
    .map((p) => p.trim())
    .filter((p) => /^[A-Za-z0-9._-]+$/.test(p))
    .slice(0, MAX_VIDEOS);
}

function readListing(formData: FormData) {
  const unit = String(formData.get("areaUnit") ?? "sqft");
  const area = readNumber(formData, "area");

  return {
    kind: String(formData.get("kind") ?? ""),
    status: String(formData.get("status") ?? "review"),
    price_inr: readNumber(formData, "price"),
    area_value: area,
    area_unit: area && isAreaUnit(unit) ? unit : null,
    rate_inr: readNumber(formData, "rate"),
    images: readImages(formData),
    videos: readVideos(formData),
    title: String(formData.get("title") ?? "").trim(),
    locality: String(formData.get("locality") ?? "").trim(),
    published: formData.get("published") === "on",
    badges: readBadges(formData),
  };
}

/**
 * Create or update, depending on whether the form carries an id.
 *
 * Contributors publish straight away, so there is no draft state to move
 * through — `published` is just a visibility switch they own.
 */
export async function saveListing(
  _prev: FormState,
  formData: FormData
): Promise<FormState> {
  await requireContributor();

  const id = String(formData.get("id") ?? "").trim();
  const values = readListing(formData);

  if (!values.title) return { error: "Please give the listing a title." };
  if (!values.price_inr && !values.rate_inr)
    return { error: "Please enter an asking price or a rate, in rupees." };
  if (values.price_inr && values.price_inr > 100_000_000_000)
    return { error: "That price looks wrong. Please check the number." };
  if (!values.locality) return { error: "Please enter a locality." };
  if (String(formData.get("area") ?? "").trim() && !values.area_value)
    return { error: "Size must be a number, or left empty." };
  if (String(formData.get("rate") ?? "").trim() && !values.rate_inr)
    return { error: "Rate must be a number, or left empty." };
  if (!KINDS.includes(values.kind))
    return { error: "Please choose a property type." };
  if (formData.get("declareAuthority") !== "yes" || formData.get("declareAccuracy") !== "yes")
    return { error: "Please confirm both declarations before saving the listing." };

  const supabase = await createClient();

  const { error } = id
    ? await supabase.from("listings").update(values).eq("id", id)
    : await supabase.from("listings").insert(values);

  // A row level security refusal comes back as an ordinary error, so say
  // something more useful than the Postgres text.
  if (error) {
    return {
      error:
        error.code === "42501"
          ? "Your account is not allowed to change listings."
          : error.message,
    };
  }

  revalidatePath("/property-marketplace");
  revalidatePath("/");
  revalidatePath("/account/listings");
  redirect("/account/listings");
}

/** Show or hide a listing without deleting it. */
export async function togglePublished(formData: FormData) {
  await requireContributor();

  const id = String(formData.get("id") ?? "");
  const next = formData.get("published") !== "true";
  if (!id) return;

  const supabase = await createClient();
  await supabase.from("listings").update({ published: next }).eq("id", id);

  revalidatePath("/property-marketplace");
  revalidatePath("/");
  revalidatePath("/account/listings");
}

/** Permanent. Row level security limits this to your own rows unless admin. */
export async function deleteListing(formData: FormData) {
  await requireContributor();

  const id = String(formData.get("id") ?? "");
  if (!id) return;

  const supabase = await createClient();

  // Take the media with it, so the buckets do not collect orphans.
  const { data: row } = await supabase
    .from("listings")
    .select("images, videos")
    .eq("id", id)
    .maybeSingle();
  const images: string[] = Array.isArray(row?.images) ? row.images.map(String) : [];
  const videos: string[] = Array.isArray(row?.videos) ? row.videos.map(String) : [];
  if (images.length) await supabase.storage.from(LISTING_IMAGES_BUCKET).remove(images);
  if (videos.length) await supabase.storage.from(LISTING_VIDEOS_BUCKET).remove(videos);

  await supabase.from("listings").delete().eq("id", id);

  revalidatePath("/property-marketplace");
  revalidatePath("/");
  revalidatePath("/account/listings");
}
